version: '3.8'

services:
  api-gateway:
    build: .
    image: api-gateway:latest
    container_name: api-gateway-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"