services:
  api-gateway:
    image: lw89233/api-gateway:latest
    container_name: api-gateway-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"